// Ambient declaration for the Wails-injected window.go bridge.
// The Go binding is generated by `wails build` from ui/main.go and ui/types.go;
// this file pins the TypeScript shape so the Solid component compiles cleanly
// without runtime-reading the JS bindings codegen.
//
// Field shapes mirror ProjectDTO + ActionItemDTO in ui/types.go (Drop FE 2.6
// D1). When a future drop adds a new IPC method or a new field on a DTO,
// update both ui/types.go AND this file in the same drop — the wailsjs/go
// codegen is regenerated by `wails build`, but this ambient is the
// authoritative TypeScript contract the FE compiles against.

export {};

declare global {
  interface Window {
    go: {
      main: {
        App: {
          ListProjects(): Promise<{ ID: string; Name: string }[]>;
          ListActionItems(projectID: string): Promise<
            {
              ID: string;
              ProjectID: string;
              ParentID: string;
              Title: string;
              Kind: string;
              Role: string;
              StructuralType: string;
              LifecycleState: string;
              Priority: string;
            }[]
          >;
        };
      };
    };
  }
}
