// Ambient declaration for the Wails-injected window.go bridge.
// The Go binding is generated by `wails build` from ui/main.go and ui/types.go;
// this file pins the TypeScript shape so the Solid component compiles cleanly
// without runtime-reading the JS bindings codegen.

export {};

declare global {
  interface Window {
    go: {
      main: {
        App: {
          ListProjects(): Promise<{ ID: string; Name: string }[]>;
        };
      };
    };
  }
}
