package dispatcher

import (
	"encoding/json"
	"errors"
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"time"

	"github.com/google/uuid"

	"github.com/evanmschultz/tillsyn/internal/domain"
)

// bundle.go ships per-spawn ephemeral bundle lifecycle for the dispatcher's
// spawn pipeline. Drop 4c F.7-CORE F.7.1 owns this surface. The provisional
// `os.MkdirTemp` block in spawn.go (TODO(F.7.1) marker since 4a.19 / F.7.17.5)
// is replaced wholesale by NewBundle.
//
// Two materialization modes per the spawn architecture memory §1 and the
// closed `tillsyn.spawn_temp_root` enum on templates.Tillsyn:
//
//   - "os_tmp" (default; selected by the empty string too): bundle root is
//     os.MkdirTemp(os.TempDir(), "tillsyn-spawn-") — the canonical path for
//     ephemeral spawns. The OS reaps abandoned temp dirs eventually; the
//     dispatcher cleanup hook (Drop 4a Wave 2.7) reaps on terminal-state.
//   - "project": bundle root is <projectRoot>/.tillsyn/spawns/<spawn-id>/.
//     Used when the dev wants forensics under the worktree (e.g. for
//     post-mortem inspection); F.7.7 lands the gitignore auto-add when this
//     mode is selected.
//
// Bundle layout follows the cross-CLI shell vs CLI-specific subtree split per
// planner-review §6.1: <Root>/manifest.json, <Root>/system-prompt.md,
// <Root>/system-append.md, <Root>/stream.jsonl, <Root>/context/ are
// cross-CLI; <Root>/plugin/... (claude) and future <Root>/codex_home/...
// (codex) are adapter-owned and materialized by the CLIAdapter inside
// BuildCommand — NewBundle does NOT pre-create them.
//
// F.7.8 orphan scan + cleanup-on-terminal-state hook are explicitly OUT OF
// SCOPE for this droplet — Bundle.Cleanup is a deferred-friendly idempotent
// reaper, but wiring it to the dispatcher's monitor terminal-state observer
// is followup work owned by F.7.8.

// SpawnTempRootOSTmp selects the OS-temp-dir bundle materialization mode
// (the canonical default). Equivalent to the empty string at the schema
// layer per templates.Tillsyn.SpawnTempRoot's consumer-time-default
// convention.
const SpawnTempRootOSTmp = "os_tmp"

// SpawnTempRootProject selects the under-worktree bundle materialization
// mode. Bundles land at <projectRoot>/.tillsyn/spawns/<spawn-id>/.
const SpawnTempRootProject = "project"

// ErrInvalidBundleInput is returned by NewBundle when one of its inputs
// fails the closed contract: spawnTempRoot outside the {"", "os_tmp",
// "project"} enum, empty projectRoot when project mode is selected, or
// empty action-item ID. Callers detect this via errors.Is and route the
// action item to a "bundle materialization failed" failure. The sentinel
// is distinct from ErrInvalidSpawnInput because callers (the dispatcher's
// monitor) may want to disambiguate template-level invalid inputs from
// runtime bundle-lifecycle invalid inputs.
var ErrInvalidBundleInput = errors.New("dispatcher: invalid bundle input")

// Bundle carries the lifecycle state for one per-spawn ephemeral bundle.
// Fields are populated by NewBundle and consumed by the cleanup hook +
// manifest writer. The companion BundlePaths struct (in cli_adapter.go)
// is the serializable adapter-facing handle adapters consume via
// CLIAdapter.BuildCommand — Bundle wraps BundlePaths plus the lifecycle
// metadata (SpawnID, StartedAt, Mode) that adapters do not need.
//
// Bundle is a value type. Copies share the same on-disk directory; the
// dispatcher creates exactly one Bundle per spawn and passes it by value
// into the cleanup goroutine, then discards it.
type Bundle struct {
	// SpawnID is the per-spawn UUID used as the directory basename in
	// project mode and embedded in the manifest. Generated by NewBundle
	// via uuid.NewString() — the dispatcher does not pass an ID in.
	SpawnID string

	// Mode is the resolved spawn-temp-root mode after empty-string
	// resolution: either SpawnTempRootOSTmp or SpawnTempRootProject.
	// Never the empty string.
	Mode string

	// StartedAt is the timestamp NewBundle was called. The manifest's
	// started_at field is sourced from this; ManifestMetadata.StartedAt
	// can override at WriteManifest time when the caller has a more
	// authoritative timestamp (e.g. cmd.Start success time).
	StartedAt time.Time

	// Paths is the serializable adapter-facing handle: Root,
	// SystemPromptPath, SystemAppendPath, StreamLogPath, ManifestPath,
	// ContextDir. Adapters consume Paths via BuildCommand without
	// needing the lifecycle metadata above.
	Paths BundlePaths
}

// ManifestMetadata is the structured payload Bundle.WriteManifest serializes
// to <Root>/manifest.json. The shape is the cross-CLI shell per the spawn
// architecture memory §2: spawn_id, action_item_id, kind, claude_pid,
// started_at, paths, bundle_path.
//
// Per Drop 4c F.7-CORE F.7.1 REV-4: NO CLIKind field — F.7.17.6 is the sole
// owner of manifest.cli_kind and lands it in a follow-up droplet.
//
// ClaudePID is declared HERE per the spawn architecture memory §2 / §8
// canonical field set, but the field's runtime invocation timing
// (UpdateManifestPID call after `cmd.Start()` returns success) is owned by
// F.7.8. Default zero value carries the "spawn not yet started, leave alone"
// signal the orphan-scan in F.7.8 keys off — see ClaudePID doc-comment below
// for the contract.
type ManifestMetadata struct {
	// SpawnID is the spawn's UUID. Mirrors Bundle.SpawnID.
	SpawnID string `json:"spawn_id"`

	// ActionItemID is the domain.ActionItem.ID this spawn was dispatched
	// for. Used by orphan-scan to route reapers back to the action item
	// the bundle belongs to.
	ActionItemID string `json:"action_item_id"`

	// Kind is the action item's domain.Kind at dispatch time. Useful for
	// post-mortem categorization and for the orphan-scan to skip
	// non-spawn-bearing kinds.
	Kind domain.Kind `json:"kind"`

	// ClaudePID is the OS process ID of the spawned claude CLI process,
	// populated by (b *Bundle).UpdateManifestPID after `cmd.Start()`
	// returns success. Per spawn architecture memory §8, the zero value
	// (0) carries the "spawn not yet started, leave alone" signal — F.7.8's
	// orphan scan checks PID liveness via this field and a non-zero PID
	// allows the scanner to distinguish abandoned bundles (PID dead) from
	// pre-start bundles (PID==0) from healthy live bundles (PID alive).
	// NewBundle never sets this field; only UpdateManifestPID writes it.
	ClaudePID int `json:"claude_pid"`

	// StartedAt is the wall-clock time the bundle was created (NewBundle
	// return). Encoded as RFC 3339 via time.Time's MarshalJSON.
	StartedAt time.Time `json:"started_at"`

	// Paths mirrors the action item's domain.ActionItem.Paths slice (the
	// declared edit scope). Stored in the manifest so post-mortem tooling
	// can correlate failed bundles with the files the spawn was meant to
	// touch.
	Paths []string `json:"paths"`

	// BundlePath is the absolute filesystem path of the bundle root
	// directory. Always populated by WriteManifest at write time (sourced
	// from the receiver Bundle.Paths.Root). Used by forensic-recovery
	// tooling to walk back from a manifest fragment loaded out-of-band to
	// the bundle directory it belongs to — without this field a manifest
	// found by absolute path on disk has no self-describing way to confirm
	// its own root location matches the path it was loaded from.
	BundlePath string `json:"bundle_path"`
}

// NewBundle materializes a per-spawn bundle directory and returns a
// populated Bundle ready for adapter.BuildCommand to consume via
// Bundle.Paths.
//
// Inputs:
//
//   - item: the action item the spawn is dispatched for. NewBundle reads
//     item.ID for input validation and item.Kind / item.Paths for the
//     manifest payload (consumed via WriteManifest later).
//   - spawnTempRoot: closed-enum string from templates.Tillsyn.SpawnTempRoot.
//     Empty / "os_tmp" → OS temp dir mode; "project" → under-worktree mode.
//     Any other value → ErrInvalidBundleInput.
//   - projectRoot: absolute path of the project's primary worktree.
//     REQUIRED when spawnTempRoot resolves to "project"; ignored in
//     "os_tmp" mode but typically passed regardless so the dispatcher's
//     code path is symmetric.
//
// Returns ErrInvalidBundleInput wrapped with a reason on failure.
//
// The bundle directory is created with 0o700 perms (project mode) or
// inherits os.MkdirTemp's default (typically 0o700 on POSIX). Subdirs
// like ContextDir are NOT pre-created — adapters and the F.7.18
// aggregator materialize their own subtrees lazily.
func NewBundle(item domain.ActionItem, spawnTempRoot string, projectRoot string) (Bundle, error) {
	if strings.TrimSpace(item.ID) == "" {
		return Bundle{}, fmt.Errorf("%w: action item ID is empty", ErrInvalidBundleInput)
	}

	mode, err := resolveSpawnTempRoot(spawnTempRoot)
	if err != nil {
		return Bundle{}, err
	}

	spawnID := uuid.NewString()
	startedAt := time.Now().UTC()

	root, err := materializeBundleRoot(mode, projectRoot, spawnID)
	if err != nil {
		return Bundle{}, err
	}

	return Bundle{
		SpawnID:   spawnID,
		Mode:      mode,
		StartedAt: startedAt,
		Paths: BundlePaths{
			Root:             root,
			SystemPromptPath: filepath.Join(root, "system-prompt.md"),
			// SystemAppendPath stays empty — F.7.3b populates when the
			// system_append_template_path knob lands.
			SystemAppendPath: "",
			StreamLogPath:    filepath.Join(root, "stream.jsonl"),
			ManifestPath:     filepath.Join(root, "manifest.json"),
			ContextDir:       filepath.Join(root, "context"),
		},
	}, nil
}

// resolveSpawnTempRoot maps the schema-layer SpawnTempRoot string to the
// runtime mode constant. Empty resolves to SpawnTempRootOSTmp per the
// consumer-time-default convention; "os_tmp" and "project" pass through;
// any other value returns ErrInvalidBundleInput.
//
// Defense-in-depth: the templates.Load validator already rejects bogus
// values, but the dispatcher may receive a hand-constructed
// templates.Tillsyn (e.g. from tests or future programmatic-config
// paths) where the validator did not run. Re-checking here keeps the
// bundle materializer self-sufficient.
func resolveSpawnTempRoot(spawnTempRoot string) (string, error) {
	switch spawnTempRoot {
	case "", SpawnTempRootOSTmp:
		return SpawnTempRootOSTmp, nil
	case SpawnTempRootProject:
		return SpawnTempRootProject, nil
	default:
		return "", fmt.Errorf("%w: spawn_temp_root %q not in {%q, %q, %q}",
			ErrInvalidBundleInput, spawnTempRoot, "", SpawnTempRootOSTmp, SpawnTempRootProject)
	}
}

// materializeBundleRoot creates the bundle directory on disk per the
// resolved mode and returns its absolute path. In OS-temp mode the path
// is generated by os.MkdirTemp (uses os.TempDir() + the "tillsyn-spawn-"
// prefix). In project mode the path is <projectRoot>/.tillsyn/spawns/<id>
// — projectRoot must be non-empty.
//
// The function is internal (lowercase) so future bundle-creation paths
// (rerun, retry, re-bind) can plug into the same materialization without
// going through NewBundle's input-validation.
func materializeBundleRoot(mode string, projectRoot string, spawnID string) (string, error) {
	switch mode {
	case SpawnTempRootOSTmp:
		root, err := os.MkdirTemp("", "tillsyn-spawn-")
		if err != nil {
			return "", fmt.Errorf("dispatcher: create os_tmp bundle root: %w", err)
		}
		return root, nil
	case SpawnTempRootProject:
		if strings.TrimSpace(projectRoot) == "" {
			return "", fmt.Errorf("%w: projectRoot is empty (required for project mode)", ErrInvalidBundleInput)
		}
		// .tillsyn/spawns/ may not exist yet on a fresh worktree; create
		// the parent chain idempotently. 0o700 keeps the per-spawn dir
		// tooling-private — the bundle holds prompt bodies that may
		// carry action-item structural data.
		root := filepath.Join(projectRoot, ".tillsyn", "spawns", spawnID)
		if err := os.MkdirAll(root, 0o700); err != nil {
			return "", fmt.Errorf("dispatcher: create project bundle root: %w", err)
		}
		return root, nil
	default:
		// Should be unreachable: resolveSpawnTempRoot rejects bogus
		// modes upstream. Defensive return for forward-compat.
		return "", fmt.Errorf("%w: unsupported mode %q", ErrInvalidBundleInput, mode)
	}
}

// Cleanup removes the bundle's on-disk directory and everything beneath it.
// The function is idempotent: a second call after a successful first call
// returns nil because os.RemoveAll treats a non-existent path as success.
//
// Cleanup is intentionally NOT wired to the dispatcher's monitor
// terminal-state observer in this droplet — F.7.8 (orphan scan +
// cleanup-on-terminal-state) owns that integration. Today callers `defer
// bundle.Cleanup()` themselves when they want immediate reap-on-return
// semantics; the spawn pipeline relies on the F.7.8 hook to fire once
// the spawn reaches its terminal state.
//
// Errors from os.RemoveAll surface unwrapped — the caller already knows
// it is a cleanup error from the call site.
func (b Bundle) Cleanup() error {
	if b.Paths.Root == "" {
		return nil
	}
	return os.RemoveAll(b.Paths.Root)
}

// WriteManifest serializes the supplied metadata to <Root>/manifest.json
// using the atomic write-temp-then-rename pattern (write to
// manifest.json.tmp → fsync the temp file → rename onto the final name).
// Empty metadata fields are written as their JSON zero values (empty
// string, null time, nil slice).
//
// The function auto-populates ManifestMetadata.BundlePath from the receiver
// Bundle.Paths.Root before writing — callers do NOT need to set BundlePath
// themselves (and any value they DO set is overwritten with the receiver's
// Root). Every other field is taken verbatim from the supplied metadata so
// cross-droplet schema additions (F.7.17.6's CLIKind etc.) plug in by
// extending ManifestMetadata, not by reaching into Bundle internals.
//
// Permissions: the file is created with 0o600 — the bundle directory is
// per-spawn and tooling-private. The manifest may reference action-item
// IDs the dev does not want broadcast to other users on the host.
//
// Atomicity: the write-then-rename pattern prevents readers (F.7.8 orphan
// scan, forensic recovery tooling) from observing a half-written manifest.
// The temp file is fsync'd before rename so a crash between rename and
// dir-fsync still leaves the file durable on the platforms that respect
// fsync ordering. Parent-directory fsync is intentionally omitted today —
// the spawn architecture memory §1 treats bundles as best-effort forensic
// records, NOT crash-survival-critical state, and the cost of dir-fsync on
// every spawn outweighs the marginal forensic improvement. F.7.8 may
// revisit if the orphan-scan reveals a real-world correctness gap.
func (b Bundle) WriteManifest(metadata ManifestMetadata) error {
	if b.Paths.ManifestPath == "" {
		return fmt.Errorf("%w: bundle ManifestPath is empty", ErrInvalidBundleInput)
	}
	metadata.BundlePath = b.Paths.Root
	return writeManifestAtomic(b.Paths.ManifestPath, metadata)
}

// ReadManifest reads <bundlePath>/manifest.json and decodes it into a
// ManifestMetadata. The bundlePath argument is the bundle root directory
// (NOT the manifest.json file path itself); the function appends
// "manifest.json" to the supplied path so callers can pass the same
// directory handle they originally received from NewBundle.
//
// Error contract:
//
//   - Missing manifest file: returned error wraps os.ErrNotExist so callers
//     can detect via errors.Is(err, os.ErrNotExist). F.7.8's orphan scan
//     uses this branch to flag bundles whose dispatcher crashed before
//     WriteManifest fired.
//   - Malformed JSON / unparseable payload: returned error is non-nil and
//     wraps the underlying json.Unmarshal error with a "decode manifest"
//     prefix. Forensic tooling typically logs and skips such manifests.
//   - File-system read errors (permission denied, etc.): wrapped with a
//     "read manifest" prefix.
func ReadManifest(bundlePath string) (ManifestMetadata, error) {
	if strings.TrimSpace(bundlePath) == "" {
		return ManifestMetadata{}, fmt.Errorf("%w: bundlePath is empty", ErrInvalidBundleInput)
	}
	manifestPath := filepath.Join(bundlePath, "manifest.json")
	contents, err := os.ReadFile(manifestPath)
	if err != nil {
		// os.ReadFile already returns errors satisfying errors.Is(err,
		// os.ErrNotExist) for missing files; wrap with %w so the
		// sentinel survives the additional context layer.
		return ManifestMetadata{}, fmt.Errorf("dispatcher: read manifest %s: %w", manifestPath, err)
	}
	var metadata ManifestMetadata
	if err := json.Unmarshal(contents, &metadata); err != nil {
		return ManifestMetadata{}, fmt.Errorf("dispatcher: decode manifest %s: %w", manifestPath, err)
	}
	return metadata, nil
}

// UpdateManifestPID reads the existing manifest, sets ClaudePID to pid, and
// writes the result back atomically. All other fields are preserved
// verbatim from disk — including BundlePath, which is re-asserted from the
// receiver's Root via the WriteManifest contract.
//
// F.7.8 (orphan-scan + cleanup-on-terminal-state hook) will invoke this
// method from the dispatcher's spawn pipeline immediately after
// `cmd.Start()` returns success. Per spawn architecture memory §8, the
// zero-value PID==0 left by NewBundle / WriteManifest carries the "spawn
// not yet started, leave alone" signal that the orphan scan keys off; the
// first non-zero write here flips the bundle into "spawn live, monitor for
// liveness" state.
//
// Error contract:
//
//   - Missing manifest file: error wraps os.ErrNotExist (callers should
//     treat this as a programmer error — UpdateManifestPID should never
//     run on a bundle whose WriteManifest was not called first).
//   - Malformed manifest: error is non-nil with a "decode manifest" prefix.
//   - Write errors: wrapped with the same atomic-write error semantics as
//     WriteManifest.
//
// Concurrency: there is no internal locking — the spawn architecture
// assumes a single writer per bundle (the dispatcher's monitor goroutine).
// Two concurrent UpdateManifestPID calls on the same bundle race; the
// rename-based write semantics guarantee no torn writes, but last-write-
// wins applies.
func (b Bundle) UpdateManifestPID(pid int) error {
	if b.Paths.Root == "" || b.Paths.ManifestPath == "" {
		return fmt.Errorf("%w: bundle is zero-value", ErrInvalidBundleInput)
	}
	metadata, err := ReadManifest(b.Paths.Root)
	if err != nil {
		return fmt.Errorf("dispatcher: update manifest PID: %w", err)
	}
	metadata.ClaudePID = pid
	// Re-assert BundlePath from the receiver so a manifest authored by a
	// different code path that left BundlePath empty still self-heals on
	// the next update.
	metadata.BundlePath = b.Paths.Root
	return writeManifestAtomic(b.Paths.ManifestPath, metadata)
}

// writeManifestAtomic serializes metadata to manifestPath using the
// write-temp-then-fsync-then-rename pattern. The temp file is created
// alongside the target with a ".tmp" suffix so the rename is atomic on
// POSIX filesystems (same-directory rename is atomic per POSIX rename(2)).
//
// Both WriteManifest and UpdateManifestPID funnel through this helper so
// the durability + atomicity contract stays consistent across write paths.
//
// On error the partially-written temp file is best-effort removed so a
// failed write does not leak a `.tmp` sibling next to the target.
func writeManifestAtomic(manifestPath string, metadata ManifestMetadata) error {
	payload, err := json.MarshalIndent(metadata, "", "  ")
	if err != nil {
		return fmt.Errorf("dispatcher: marshal manifest: %w", err)
	}
	tmpPath := manifestPath + ".tmp"
	f, err := os.OpenFile(tmpPath, os.O_RDWR|os.O_CREATE|os.O_TRUNC, 0o600)
	if err != nil {
		return fmt.Errorf("dispatcher: open manifest temp file: %w", err)
	}
	if _, err := f.Write(payload); err != nil {
		_ = f.Close()
		_ = os.Remove(tmpPath)
		return fmt.Errorf("dispatcher: write manifest payload: %w", err)
	}
	if err := f.Sync(); err != nil {
		_ = f.Close()
		_ = os.Remove(tmpPath)
		return fmt.Errorf("dispatcher: fsync manifest temp file: %w", err)
	}
	if err := f.Close(); err != nil {
		_ = os.Remove(tmpPath)
		return fmt.Errorf("dispatcher: close manifest temp file: %w", err)
	}
	if err := os.Rename(tmpPath, manifestPath); err != nil {
		_ = os.Remove(tmpPath)
		return fmt.Errorf("dispatcher: rename manifest into place: %w", err)
	}
	return nil
}
