package domain

import "errors"

// ErrInvalidID and related errors describe validation and runtime failures.
var (
	ErrInvalidID                   = errors.New("invalid id")
	ErrInvalidName                 = errors.New("invalid name")
	ErrInvalidTitle                = errors.New("invalid title")
	ErrInvalidSummary              = errors.New("invalid summary")
	ErrInvalidBodyMarkdown         = errors.New("invalid body markdown")
	ErrInvalidPriority             = errors.New("invalid priority")
	ErrInvalidPosition             = errors.New("invalid position")
	ErrInvalidColumnID             = errors.New("invalid column id")
	ErrInvalidParentID             = errors.New("invalid parent id")
	ErrInvalidScopeType            = errors.New("invalid scope type")
	ErrInvalidScopeID              = errors.New("invalid scope id")
	ErrInvalidTargetID             = errors.New("invalid target id")
	ErrInvalidTargetType           = errors.New("invalid target type")
	ErrInvalidKind                 = errors.New("invalid kind")
	ErrInvalidKindID               = errors.New("invalid kind id")
	ErrInvalidKindAppliesTo        = errors.New("invalid kind applies_to")
	ErrKindNotAllowed              = errors.New("kind is not allowed for this project")
	ErrKindNotFound                = errors.New("kind definition not found")
	ErrInvalidKindPayload          = errors.New("invalid kind payload")
	ErrInvalidKindPayloadSchema    = errors.New("invalid kind payload schema")
	ErrInvalidRole                 = errors.New("invalid role")
	ErrInvalidStructuralType       = errors.New("invalid structural type")
	ErrInvalidDropNumber           = errors.New("invalid drop number")
	ErrInvalidPaths                = errors.New("invalid paths")
	ErrInvalidPackages             = errors.New("invalid packages")
	ErrInvalidFiles                = errors.New("invalid files")
	ErrInvalidLanguage             = errors.New("invalid language")
	ErrInvalidRepoPath             = errors.New("invalid repo path")
	ErrInvalidLifecycleState       = errors.New("invalid lifecycle state")
	ErrInvalidActorType            = errors.New("invalid actor type")
	ErrInvalidAttentionState       = errors.New("invalid attention state")
	ErrInvalidAttentionKind        = errors.New("invalid attention kind")
	ErrInvalidHandoffStatus        = errors.New("invalid handoff status")
	ErrInvalidHandoffTransition    = errors.New("invalid handoff transition")
	ErrInvalidAuthRequestPath      = errors.New("invalid auth request path")
	ErrInvalidAuthRequestState     = errors.New("invalid auth request state")
	ErrInvalidAuthRequestTTL       = errors.New("invalid auth request ttl")
	ErrInvalidAuthRequestRole      = errors.New("invalid auth request role")
	ErrInvalidAuthContinuation     = errors.New("invalid auth request continuation")
	ErrAuthRequestClaimMismatch    = errors.New("auth request claim mismatch")
	ErrInvalidCapabilityRole       = errors.New("invalid capability role")
	ErrInvalidCapabilityAction     = errors.New("invalid capability action")
	ErrInvalidCapabilityDelegation = errors.New("invalid capability delegation")
	ErrInvalidCapabilityScope      = errors.New("invalid capability scope")
	ErrInvalidCapabilityToken      = errors.New("invalid capability token")
	ErrInvalidCapabilityExpiry     = errors.New("invalid capability expiry")
	ErrMutationLeaseRequired       = errors.New("mutation lease is required")
	ErrMutationLeaseInvalid        = errors.New("mutation lease is invalid")
	ErrMutationLeaseExpired        = errors.New("mutation lease is expired")
	ErrMutationLeaseRevoked        = errors.New("mutation lease is revoked")
	ErrOrchestratorOverlap         = errors.New("overlapping orchestrator lease blocked")
	ErrOverrideTokenRequired       = errors.New("override token is required for overlapping orchestrator lease")
	ErrOverrideTokenInvalid        = errors.New("override token is invalid")
	ErrTransitionBlocked           = errors.New("transition blocked by completion contract")
	ErrAuthRequestNotPending       = errors.New("auth request is not pending")
	ErrAuthRequestExpired          = errors.New("auth request is expired")
)
