package pretoolgate

import (
	"context"
	"encoding/json"
)

// editTools is the set of tool names that grant write access to files.
// Mirrors EDIT_TOOLS from the proven hook (ta_action_gate.py line 59).
var editTools = map[string]struct{}{
	"Edit":         {},
	"Write":        {},
	"MultiEdit":    {},
	"NotebookEdit": {},
}

// Event is the parsed PreToolUse JSON payload delivered by Claude Code to the
// gate hook. JSON tags match the proven hook's Python keys (ta_action_gate.py
// main() lines 303-308). The gate reads TILL_GATE_ALLOWLIST from os.Getenv
// inside ResolveAllowlist — env resolution is kept in ONE place (A.2).
type Event struct {
	ToolName       string         `json:"tool_name"`
	ToolInput      map[string]any `json:"tool_input"`
	Cwd            string         `json:"cwd"`
	AgentID        string         `json:"agent_id"`
	AgentType      string         `json:"agent_type"`
	TranscriptPath string         `json:"transcript_path"`
}

// Decision is the gate's verdict for a single PreToolUse event.
// When Defer is true, the caller writes nothing to stdout and exits 0
// (the dev keeps normal control). Otherwise Permission is "allow" or "deny"
// and Reason carries the human-readable explanation.
type Decision struct {
	Defer      bool
	Permission string // "allow" | "deny"
	Reason     string
}

// hookSpecificOutput is the JSON envelope written to stdout for a gated
// (non-deferred) decision. Ports Python _explicit_allow() / _deny() from
// ta_action_gate.py lines 70-92.
type hookSpecificOutput struct {
	HookSpecificOutput hookOutputBody `json:"hookSpecificOutput"`
}

type hookOutputBody struct {
	HookEventName            string `json:"hookEventName"`
	PermissionDecision       string `json:"permissionDecision"`
	PermissionDecisionReason string `json:"permissionDecisionReason"`
}

// MarshalDecision encodes a non-deferred Decision as the JSON shape expected
// by the Claude Code PreToolUse hook protocol. Returns nil, nil for deferred
// decisions (caller writes nothing).
func MarshalDecision(d Decision) ([]byte, error) {
	if d.Defer {
		return nil, nil
	}
	out := hookSpecificOutput{
		HookSpecificOutput: hookOutputBody{
			HookEventName:            "PreToolUse",
			PermissionDecision:       d.Permission,
			PermissionDecisionReason: d.Reason,
		},
	}
	return json.Marshal(out)
}

// Decide evaluates a PreToolUse Event against its resolved allowlist and
// returns the gate Decision. It wires A.2 (ResolveAllowlist), A.3
// (editAllowed), A.4 (gitMutation — the hardcoded baseline floor), and A.5
// (bashForbidden, bashWriteVector) into the single enforcement entrypoint.
//
// Decision logic (ports proven-hook main() lines 329-396, fix #5 applied):
//
//  1. Resolve allowlist via A.2. If nil (ungated / orchestrator) → Defer.
//  2. Branch on ToolName:
//     - EDIT_TOOLS: deny if target file is not in spec.Edit (deny-all when
//     spec.Edit is nil-or-empty, preserving the "absent key = deny-all" rule).
//     - Bash: gitMutation floor FIRST (A.4, orch-independent 28-verb set),
//     then bashForbidden (A.5, orch-supplied bash_deny), then bashWriteVector
//     (A.5) if spec.Edit != nil (edit-scoped agent shell bypass check).
//     - All other tools: allow (Read/Grep/Glob/mcp_* etc.).
//
// Decide is fail-open: it never panics on malformed input. Type assertions on
// ToolInput use the two-value form and fall through to empty string on miss.
func Decide(ev Event) Decision {
	spec := ResolveAllowlist(context.Background(), ev.AgentID, ev.AgentType, ev.TranscriptPath)
	if spec == nil {
		// Ungated: orchestrator or un-scoped caller — defer to normal control.
		return Decision{Defer: true}
	}

	decision := "allow"
	reason := ""

	if _, isEdit := editTools[ev.ToolName]; isEdit {
		// EDIT_TOOLS branch: target must be in spec.Edit.
		// spec.Edit == nil (absent key) and spec.Edit == [] (present-empty) both
		// map to deny-all, matching Python allowlist.get("edit", []) which returns []
		// when the key is absent.
		var allowed []string
		if spec.Edit != nil {
			allowed = spec.Edit
		}
		target, _ := ev.ToolInput["file_path"].(string)
		if target == "" {
			target, _ = ev.ToolInput["notebook_path"].(string)
		}
		if !editAllowed(target, allowed, ev.Cwd) {
			decision = "deny"
			reason = "BLOCKED by the dispatch allowlist passed at call time: this " +
				"agent may only edit " + formatAllowed(allowed) + ", but the prompt directed an edit " +
				"to '" + target + "', which is NOT on the allowed list. This is a " +
				"prompt-vs-allowlist contradiction. Do NOT edit this file. STOP " +
				"and report the contradiction to the orchestrator."
		}
	} else if ev.ToolName == "Bash" {
		cmd, _ := ev.ToolInput["command"].(string)
		deny := spec.BashDeny

		// BASELINE FIRST (fix #5, proven-hook line 354):
		// gitMutation fires UNCONDITIONALLY before the orch-supplied bash_deny pass.
		// This prevents the "forgetful orchestrator" failure mode: even when bash_deny
		// omits git verbs, git commit/push/etc. are denied as a hardcoded floor.
		hit, ok := gitMutation(cmd)
		if !ok {
			hit, ok = bashForbidden(cmd, deny)
		}
		if ok {
			decision = "deny"
			reason = "BLOCKED by the dispatch allowlist passed at call time: the " +
				"command matches the forbidden pattern '" + hit + "' (e.g. git " +
				"mutation / mage install / dependency mutation), which this " +
				"agent is not permitted to run. This is a prompt-vs-allowlist " +
				"contradiction. Do NOT run it. STOP and report the contradiction " +
				"to the orchestrator."
		} else if spec.Edit != nil {
			// Edit-scoped agent: shell file-write bypass check (A.5 bashWriteVector).
			// Only applies when spec.Edit is non-nil ("edit" key was present in the
			// allowlist JSON), matching Python `elif "edit" in allowlist`.
			if wv, ok2 := bashWriteVector(cmd); ok2 {
				decision = "deny"
				reason = "BLOCKED by the dispatch allowlist passed at call time: this agent's file edits " +
					"are confined to " + formatAllowed(spec.Edit) + " via the Edit/Write tools, but this " +
					"Bash command uses a shell file-write/mutation vector (" + wv + ") — the " +
					"cat>/python/sed -i/tee bypass. Shell-based file mutation is NOT permitted for an " +
					"edit-scoped agent. Do NOT run it. STOP and report the contradiction to the " +
					"orchestrator."
			}
		}
	}
	// All other tools (Read/Grep/Glob/mcp_*) fall through to allow.

	return Decision{Permission: decision, Reason: reason}
}

// formatAllowed returns a compact string representation of the allowed list
// for embedding in deny reason messages. Returns "[]" for an empty or nil list.
func formatAllowed(allowed []string) string {
	if len(allowed) == 0 {
		return "[]"
	}
	b, err := json.Marshal(allowed)
	if err != nil {
		return "[]"
	}
	return string(b)
}
